[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 